# Book settings
title: Artificial intelligence, Concepts, Challenges, and Opportunities
author: Petri Välisuo
logo: figures/ai.jpg

latex:
  latex_documents:
    targetname: book.tex
    
sphinx:
    config:
        bibtex_reference_style: label

bibtex_bibfiles:
    - references.bib

